### ISSUE TITLE
Wire Diagram issue

### ISSUE THREAD

**Issue by kingpinzs** [r-cute/rcute-cozmars-server#28]
The vcc wire for the audio amp is on the wrong pin it should be on the power pin and not the data pin for the amp power in the diagram

**Comment by hyansuper** [comment]
I wanted to be able to turn on and off the audio amp, so I connect amp power to data pin. I was worried about interference between audio input and output because they share i2s bus
but the easier way is to connect to power pin as you said, it works, except the speaker produce a click sound every time just before recording starts, but it's not a big problem

**Comment by hyansuper** [comment]
The PCA9685 channels can turn fully on/off, see https://learn.adafruit.com/16-channel-pwm-servo-driver?view=all#using-as-gpio-2980401-5
